"0","import matplotlib.pyplot as plt"
"0","x = [10, 8, 13, 9, 11, 14, 6, 4 , 12, 7, 5]"
"0","y = [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68]"
"0","plt.scatter(x, y)"
"1","<matplotlib.collections.PathCollection object at 0x000001D5CD2560F0>
"
"0","plt.show(path="""")"
"2","Traceback (most recent call last):
  File ""<string>"", line 1, in <module>
  File ""[90m]8;line = 16;file://C:\Users\gisel\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\call.pyC:\Users\gisel\AppData\Local\R\win-library\4.3\reticulate\python\rpytools\call.py]8;;[39m"", line 16, in python_function
    raise error
RuntimeError: argumento 'path' inv√°lido
"
